//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalCipherSolver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicalCipherSolver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TH 116997844
        ///HE 100689263
        ///IN 87674002
        ///ER 77134382
        ///AN 69775179
        ///RE 60923600
        ///ES 57070453
        ///ON 56915252
        ///ST 54018399
        ///NT 50701084
        ///EN 48991276
        ///AT 48274564
        ///ED 46647960
        ///ND 46194306
        ///TO 46115188
        ///OR 45725191
        ///EA 43329810
        ///TI 42888666
        ///AR 42353262
        ///TE 42295813
        ///NG 38567365
        ///AL 38211584
        ///IT 37938534
        ///AS 37773878
        ///IS 37349981
        ///HA 35971841
        ///ET 32872552
        ///SE 31532272
        ///OU 31112284
        ///OF 30540904
        ///LE 30383262
        ///SA 30080131
        ///VE 29320973
        ///RO 29230770
        ///RA 28645577
        ///RI 27634643
        ///HI 27495342
        ///NE 27331675
        ///ME 27237733
        ///DE  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bigrams {
            get {
                return ResourceManager.GetString("Bigrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ngrams_txt_README {
            get {
                object obj = ResourceManager.GetObject("ngrams_txt_README", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TION 13168375
        ///NTHE 11234972
        ///THER 10218035
        ///THAT 8980536
        ///OFTH 8132597
        ///FTHE 8100836
        ///THES 7717675
        ///WITH 7627991
        ///INTH 7261789
        ///ATIO 7104943
        ///OTHE 6900574
        ///TTHE 6553056
        ///DTHE 6470280
        ///INGT 6461147
        ///ETHE 6135216
        ///SAND 5996705
        ///STHE 5748611
        ///HERE 5630500
        ///THEC 5466071
        ///MENT 4968019
        ///THEM 4911484
        ///RTHE 4862875
        ///THEP 4458634
        ///FROM 4361347
        ///THIS 4344608
        ///TING 4291641
        ///THEI 4217321
        ///NGTH 4162753
        ///IONS 4045101
        ///ANDT 4020364
        ///ONTH 3976144
        ///TOTH 3911094
        ///EDTO 3886447
        ///THEF 3873133
        ///THEY 3809433
        ///HAVE 3735139
        ///EDTH  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Quadgrams {
            get {
                return ResourceManager.GetString("Quadgrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE 77534223
        ///AND 30997177
        ///ING 30679488
        ///ENT 17902107
        ///ION 17769261
        ///HER 15277018
        ///FOR 14686159
        ///THA 14222073
        ///NTH 14115952
        ///INT 13656197
        ///ERE 13287155
        ///TIO 13285065
        ///TER 12769843
        ///EST 11956466
        ///ERS 11823017
        ///ATI 11227573
        ///HAT 10900482
        ///ATE 10712298
        ///ALL 10501105
        ///ETH 10304110
        ///HES 10189449
        ///VER 10156140
        ///HIS 10051039
        ///OFT 9434246
        ///ITH 9142241
        ///FTH 9036651
        ///STH 9024058
        ///OTH 8869058
        ///RES 8835871
        ///ONT 8757161
        ///DTH 8745845
        ///ARE 8741156
        ///REA 8700830
        ///EAR 8697937
        ///WAS 8640940
        ///SIN 8629893
        ///STO 8556837
        ///TTH 8476 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Trigrams {
            get {
                return ResourceManager.GetString("Trigrams", resourceCulture);
            }
        }
    }
}
