//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassicalCipherSolver.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassicalCipherSolver.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STCG KBIYT MVYUTYZ,
        ///V JGKHJ JUCJ PDK CBS JUT OCZVYP CJ JVGEVJQKOTG CGT CYY MTYY CBS JUCJ PDK TBWDPTS JUT HXTJIUTH V HTBJ PDK YCHJ MTTX. V UCLT TBIYDHTS ZP ZDHJ GTITBJ VZEGTHHVDBH DO JUT ATCKJVOKY, VO HDZTMUCJ HJCGX YCBSHICET VB BDGODYX. V UDET CBS ATYVTLT JUCJ PDK MVYY OVBS JUTZ DO RGTCJ VBJTGTHJ. JUT OYCJ CBS DETB OVTYSH UCLT C HECGJCB ATCKJP EKBIJKCJTS AP WKHJ C OTM YCBSZCGXH DO SVHJVBIJVDB, AKJ JUTVG VHDYCJVDB ZCXTH JUTZ HJCBS DKJ TLTB ZDGT CBS VBIGTCHTH JUTVG VBJTGTHJ.
        ///DKG UDHJH UCLT ATTB ZDHJ CRGTTCA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleKeywordCiphertext {
            get {
                return ResourceManager.GetString("ExampleKeywordCiphertext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dear uncle wilhelm,
        ///i trust that you and the family at tirpitzufer are all well and that you enjoyed the sketches i sent you last week. i have enclosed my most recent impressions of the beautiful, if somewhat stark landscape in norfolk. i hope and believe that you will find them of great interest. the flat and open fields have a spartan beauty punctuated by just a few landmarks of distinction, but their isolation makes them stand out even more and increases their interest.
        ///our hosts have been most agreeab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExamplePlaintext {
            get {
                return ResourceManager.GetString("ExamplePlaintext", resourceCulture);
            }
        }
    }
}
